[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
listen.backlog = -1

pm = dynamic
pm.max_children = 20
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 15
pm.max_requests = 1000

cluster.heartbeat_freq = 1

; Improve performance
request_slowlog_timeout = 5s
slowlog = /var/log/php-fpm/www-slow.log
request_terminate_timeout = 120

; Set environment variables
clear_env = no
